all: Info-25.png\
	QuietMode-25.png\
	ManualMode-25.png\
	SignificantMode-25.png\
	QuietMode-25-negate.png\
	ManualMode-25-negate.png\
	SignificantMode-25-negate.png\
	MoveMode-25-negate.png\
	Friends-33.png\
	iBeaconOn-33.png\
	iBeaconOn2-33.png\
	Regions-33.png\
	iBeaconHot-40.png\
	iBeaconCold-40.png\
	RegionHot-40.png\
	RegionCold-40.png

iBeaconHot-40.png:iBeaconHot.svg
	./size40.sh iBeaconHot.svg

iBeaconCold-40.png:iBeaconCold.svg
	./size40.sh iBeaconCold.svg

RegionHot-40.png:RegionHot.svg
	./size40.sh RegionHot.svg

RegionCold-40.png:RegionCold.svg
	./size40.sh RegionCold.svg

iBeaconOn-33.png:iBeaconOn.svg
	./size33.sh iBeaconOn.svg

iBeaconOn2-33.png:iBeaconOn2.svg
	./size33.sh iBeaconOn2.svg

Regions-33.png:Regions.svg
	./size33.sh Regions.svg

Info-25.png:Info.svg
	./size25.sh Info.svg

QuietMode-25.png QuietMode-25-negate.png:QuietMode.svg
	./size25.sh QuietMode.svg

ManualMode-25.png ManualMode-25-negate.png:ManualMode.svg
	./size25.sh ManualMode.svg

SignificantMode-25.png SignificantMode-25-negate.png:SignificantMode.svg
	./size25.sh SignificantMode.svg

MoveMode-25.png MoveMode-25-negate.png:MoveMode.svg
	./size25.sh MoveMode.svg

Friends-33.png:Friends.svg
	./size33.sh Friends.svg
