all: Info-33.png\
	QuietMode-33.png\
	ManualMode-33.png\
	SignificantMode-33.png\
	MoveMode-33.png\
	Friends-33.png\
	Settings-33.png\
	Messaging-33.png\
	iBeaconOn-33.png\
	iBeaconOn2-33.png\
	Regions-33.png\
	iBeaconHot-40.png\
	iBeaconCold-40.png\
	RegionHot-40.png\
	RegionCold-40.png

iBeaconHot-40.png:iBeaconHot.svg
	./size40.sh iBeaconHot.svg

iBeaconCold-40.png:iBeaconCold.svg
	./size40.sh iBeaconCold.svg

RegionHot-40.png:RegionHot.svg
	./size40.sh RegionHot.svg

RegionCold-40.png:RegionCold.svg
	./size40.sh RegionCold.svg

Messaging-33.png:Messaging.svg
	./size33.sh Messaging.svg

iBeaconOn-33.png:iBeaconOn.svg
	./size33.sh iBeaconOn.svg

iBeaconOn2-33.png:iBeaconOn2.svg
	./size33.sh iBeaconOn2.svg

Regions-33.png:Regions.svg
	./size33.sh Regions.svg

Info-33.png:Info.svg
	./size33.sh Info.svg

QuietMode-33.png:QuietMode.svg
	./size33.sh QuietMode.svg

ManualMode-33.png:ManualMode.svg
	./size33.sh ManualMode.svg

SignificantMode-33.png:SignificantMode.svg
	./size33.sh SignificantMode.svg

MoveMode-33.png:MoveMode.svg
	./size33.sh MoveMode.svg

Settings-33.png:Settings.svg
	./size33.sh Settings.svg

Friends-33.png:Friends.svg
	./size33.sh Friends.svg
