all: Messaging-33.png iBeaconOn-33.png iBeaconOn2-33.png iBeaconOff-33.png iBeaconHot-40.png iBeaconCold-40.png RegionHot-40.png RegionCold-40.png

iBeaconHot-40.png:iBeaconHot.svg
	./size40.sh iBeaconHot.svg

iBeaconCold-40.png:iBeaconCold.svg
	./size40.sh iBeaconCold.svg

RegionHot-40.png:RegionHot.svg
	./size40.sh RegionHot.svg

RegionCold-40.png:RegionCold.svg
	./size40.sh RegionCold.svg

Messaging-33.png:Messaging.svg
	./size33.sh Messaging.svg

iBeaconOn-33.png:iBeaconOn.svg
	./size33.sh iBeaconOn.svg

iBeaconOn2-33.png:iBeaconOn2.svg
	./size33.sh iBeaconOn2.svg

iBeaconOff-33.png:iBeaconOff.svg
	./size33.sh iBeaconOff.svg
