source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

target 'OwnTracks' do
platform :ios, '17.0'
#pod 'mqttc/MinL', :git => 'https://github.com/ckrey/mqttc.git'
pod 'mqttc/MinL', :path => '~/mqttc'

pod 'CocoaLumberjack'
pod 'DSJSONSchemaValidation'
pod 'Sodium'
end


