source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '7.0'

pod 'CocoaLumberjack'
pod 'ABStaticTableViewController'
pod 'MQTTClient'
pod 'QRCodeReaderViewController'
pod 'objc-geohash'

target 'OwnTracks' do
end

target 'OwnTracksTests' do
end

